import { Achievement } from './Achievement';
import { AchievementReward } from './AchievementReward';
import { AchievementRewardSet } from './AchievementRewardSet';
import { Album } from './Album';
import { AlbumLevelCap } from './AlbumLevelCap';
import { Award } from './Award';
import { AwardCategory } from './AwardCategory';
import { Character } from './Character';
import { CharacterCard } from './CharacterCard';
import { CharacterCardExpItem } from './CharacterCardExpItem';
import { CharacterCardLevelCoefficient } from './CharacterCardLevelCoefficient';
import { CharacterCardRankUpItem } from './CharacterCardRankUpItem';
import { CharacterCardRankUpItemSet } from './CharacterCardRankUpItemSet';
import { CharacterTalk } from './CharacterTalk';
import { CharacterVoice } from './CharacterVoice';
import { Cooperation } from './Cooperation';
import { CoupleStory } from './CoupleStory';
import { CoupleStoryEpisode } from './CoupleStoryEpisode';
import { CriwareAdx2Acf } from './CriwareAdx2Acf';
import { CriwareAdx2Cue } from './CriwareAdx2Cue';
import { CriwareAdx2CueSheet } from './CriwareAdx2CueSheet';
import { CriwareFileMagicProCpk } from './CriwareFileMagicProCpk';
import { Currency } from './Currency';
import { ElapsedTimeRecoveringPoint } from './ElapsedTimeRecoveringPoint';
import { Event } from './Event';
import { EventAchievementReward } from './EventAchievementReward';
import { EventAlbum } from './EventAlbum';
import { EventCharacterCard } from './EventCharacterCard';
import { EventRankingReward } from './EventRankingReward';
import { EventTag } from './EventTag';
import { EventTheater } from './EventTheater';
import { EventTheaterGroup } from './EventTheaterGroup';
import { EventTheaterGroupSchedule } from './EventTheaterGroupSchedule';
import { EventThemeMusic } from './EventThemeMusic';
import { FanCountTalk } from './FanCountTalk';
import { Gacha } from './Gacha';
import { GachaBox } from './GachaBox';
import { GachaTicket } from './GachaTicket';
import { GuerrillaLive } from './GuerrillaLive';
import { GuerrillaLiveMusic } from './GuerrillaLiveMusic';
import { GuerrillaPassRecoverItem } from './GuerrillaPassRecoverItem';
import { HeartBoost } from './HeartBoost';
import { HeartRecoverItem } from './HeartRecoverItem';
import { HomeTalk } from './HomeTalk';
import { HomeTalkMessage } from './HomeTalkMessage';
import { IndependentScenario } from './IndependentScenario';
import { ItemReference } from './ItemReference';
import { ItemType } from './ItemType';
import { LimitedDropItemSet } from './LimitedDropItemSet';
import { LoginBonus } from './LoginBonus';
import { LoginBonusDay } from './LoginBonusDay';
import { Merchandise } from './Merchandise';
import { Music } from './Music';
import { MusicalScore } from './MusicalScore';
import { MusicPart } from './MusicPart';
import { MusicPartAchievement } from './MusicPartAchievement';
import { MusicPartAchievementThreshold } from './MusicPartAchievementThreshold';
import { MusicPartLevel } from './MusicPartLevel';
import { MusicPartLevelReward } from './MusicPartLevelReward';
import { MusicPartLock } from './MusicPartLock';
import { MVEvent } from './MVEvent';
import { MVEventThemePanel } from './MVEventThemePanel';
import { MVEventThemePanelSet } from './MVEventThemePanelSet';
import { MVLibrary } from './MVLibrary';
import { PaidCurrency } from './PaidCurrency';
import { PlayerLevel } from './PlayerLevel';
import { PlayerLevelReward } from './PlayerLevelReward';
import { PlayerProfile } from './PlayerProfile';
import { ScenarioEvent } from './ScenarioEvent';
import { SceneCard } from './SceneCard';
import { SceneCardAcquisitionRoute } from './SceneCardAcquisitionRoute';
import { SceneCardRouteDetail } from './SceneCardRouteDetail';
import { ScoreBonus } from './ScoreBonus';
import { SeasonRoad } from './SeasonRoad';
import { SeasonRoadLevel } from './SeasonRoadLevel';
import { SeasonRoadLevelReward } from './SeasonRoadLevelReward';
import { SeasonRoadTalk } from './SeasonRoadTalk';
import { Shop } from './Shop';
import { ShopMerchandise } from './ShopMerchandise';
import { Singer } from './Singer';
import { Skill } from './Skill';
import { SkillLevelUpItem } from './SkillLevelUpItem';
import { Song } from './Song';
import { Stamp } from './Stamp';
import { SystemAssetPack } from './SystemAssetPack';
import { SystemAssetPackItem } from './SystemAssetPackItem';
import { Tag } from './Tag';
import { TalkLive } from './TalkLive';
import { Term } from './Term';
import { TextTemplate } from './TextTemplate';
import { VoteEvent } from './VoteEvent';
import { VoteEventPublicSchedule } from './VoteEventPublicSchedule';
import { VoteEventRankingReward } from './VoteEventRankingReward';
import { VoteEventTarget } from './VoteEventTarget';
import { EventTheaterScenario } from './EventTheaterScenario';
import { CoupleStoryEpisodeScenario } from './CoupleStoryEpisodeScenario';
import { GachaInformation } from './GachaInformation';
import { MVLibraryScenario } from './MVLibraryScenario';
import { TalkLiveScenario } from './TalkLiveScenario';
import { CharacterCardLevelStat } from './extra/CharacterCardLevelStat';
import {
  GachaProbability,
  GachaRarityProbability,
} from '@/types/HWPL/extra/GachaProbabilityPack';
import { BannerAssetInfo } from './extra/BannerAssetInfo';

export type CollectionTypeName = {
  Achievements: Achievement;
  AchievementRewards: AchievementReward;
  AchievementRewardSets: AchievementRewardSet;
  Albums: Album;
  AlbumLevelCaps: AlbumLevelCap;
  Assets: any;
  BannerAssetInfo: BannerAssetInfo;
  Awards: Award;
  AwardCategories: AwardCategory;
  Characters: Character;
  CharacterCards: CharacterCard;
  CharacterCardExpItems: CharacterCardExpItem;
  CharacterCardLevelCoefficients: CharacterCardLevelCoefficient;
  CharacterCardLevelStats: CharacterCardLevelStat;
  CharacterCardRankUpItems: CharacterCardRankUpItem;
  CharacterCardRankUpItemSets: CharacterCardRankUpItemSet;
  CharacterTalks: CharacterTalk;
  CharacterVoices: CharacterVoice;
  Cooperations: Cooperation;
  CoupleStories: CoupleStory;
  CoupleStoryEpisodes: CoupleStoryEpisode;
  CoupleStoryEpisodeScenarios: CoupleStoryEpisodeScenario;
  CriwareAdx2Acfs: CriwareAdx2Acf;
  CriwareAdx2Cues: CriwareAdx2Cue;
  CriwareAdx2CueSheets: CriwareAdx2CueSheet;
  CriwareFileMagicProCpks: CriwareFileMagicProCpk;
  Currencies: Currency;
  ElapsedTimeRecoveringPoints: ElapsedTimeRecoveringPoint;
  Events: Event;
  EventAchievementRewards: EventAchievementReward;
  EventAlbums: EventAlbum;
  EventCharacterCards: EventCharacterCard;
  EventRankingRewards: EventRankingReward;
  EventTags: EventTag;
  EventTheaters: EventTheater;
  EventTheaterGroup: EventTheaterGroup;
  EventTheaterGroupSchedules: EventTheaterGroupSchedule;
  EventTheaterScenarios: EventTheaterScenario;
  EventThemeMusics: EventThemeMusic;
  FanCountTalks: FanCountTalk;
  Gachas: Gacha;
  GachaBoxes: GachaBox;
  GachaConvertedPremiumProbabilities: GachaProbability;
  GachaConvertedPremiumRarityProbabilities: GachaRarityProbability;
  GachaConvertedProbabilities: GachaProbability;
  GachaConvertedRarityProbability: GachaRarityProbability;
  GachaInformations: GachaInformation;
  GachaProbabilities: GachaProbability;
  GachaRarityProbabilities: GachaRarityProbability;
  GachaTickets: GachaTicket;
  GuerrillaLives: GuerrillaLive;
  GuerrillaLiveMusics: GuerrillaLiveMusic;
  GuerrillaPassRecoverItems: GuerrillaPassRecoverItem;
  HeartBoosts: HeartBoost;
  HeartRecoverItems: HeartRecoverItem;
  HomeTalk: HomeTalk;
  HomeTalkMessage: HomeTalkMessage;
  IndependentScenarios: IndependentScenario;
  ItemReferences: ItemReference;
  ItemTypes: ItemType;
  LimitedDropItemSets: LimitedDropItemSet;
  LoginBonuses: LoginBonus;
  LoginBonusDays: LoginBonusDay;
  Merchandises: Merchandise;
  Musics: Music;
  MusicalScores: MusicalScore;
  MusicParts: MusicPart;
  MusicPartAchievements: MusicPartAchievement;
  MusicPartAchievementThresholds: MusicPartAchievementThreshold;
  MusicPartLevels: MusicPartLevel;
  MusicPartLevelRewards: MusicPartLevelReward;
  MusicPartLocks: MusicPartLock;
  MVEvents: MVEvent;
  MVEventThemePanels: MVEventThemePanel;
  MVEventThemePanelSets: MVEventThemePanelSet;
  MVLibraries: MVLibrary;
  MVLibraryScenario: MVLibraryScenario;
  PaidCurrencies: PaidCurrency;
  PlayerLevels: PlayerLevel;
  PlayerLevelRewards: PlayerLevelReward;
  PlayerProfiles: PlayerProfile;
  ScenarioEvents: ScenarioEvent;
  SceneCards: SceneCard;
  SceneCardAcquisitionRoutes: SceneCardAcquisitionRoute;
  SceneCardRouteDetails: SceneCardRouteDetail;
  ScoreBonuses: ScoreBonus;
  SeasonRoads: SeasonRoad;
  SeasonRoadLevels: SeasonRoadLevel;
  SeasonRoadLevelRewards: SeasonRoadLevelReward;
  SeasonRoadTalks: SeasonRoadTalk;
  Shops: Shop;
  ShopMerchandises: ShopMerchandise;
  Singers: Singer;
  Skills: Skill;
  SkillLevelUpItems: SkillLevelUpItem;
  Songs: Song;
  Stamps: Stamp;
  SystemAssetPacks: SystemAssetPack;
  SystemAssetPackItems: SystemAssetPackItem;
  Tags: Tag;
  TalkLives: TalkLive;
  TalkLiveScenarios: TalkLiveScenario;
  Terms: Term;
  TextTemplates: TextTemplate;
  VoteEvents: VoteEvent;
  VoteEventPublicSchedules: VoteEventPublicSchedule;
  VoteEventRankingRewards: VoteEventRankingReward;
  VoteEventTargets: VoteEventTarget;
};
