export type Skill = {
  Id: number;
  Name: string;
  Description: string;
  Trigger: number;
  TriggerArg: string;
  Probability: number;
  Class: 1 | 11 | 21 | 31 | 32 | 40 | 41 | 42 | 90;
  Arg1: string;
  Arg2: string;
  Arg3: string;
  Arg4: string;
  Arg5: string;
  Arg6: string;
  Arg7: string;
  Arg8: string;
  Arg9: string;
  Arg10: string;
  VoiceId: number;
};
